1)
Датасет - Iris species.

2)
Размер - 150 строк.
Все признаки числовые.
Нет пропусков данных.
В датасете 50 строк с данными Iris-setosa, 50 с Iris-versicolor и 50 с Iris-virginica. Данные в датасете хорошо сбалансированы.

In [29]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.base import BaseEstimator
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

df = pandas.read_csv("Iris.csv")
df.set_index("Id", inplace=True)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [31]:
df.describe(include="all")

        SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
count      150.000000    150.000000     150.000000    150.000000          150
unique            NaN           NaN            NaN           NaN            3
top               NaN           NaN            NaN           NaN  Iris-setosa
freq              NaN           NaN            NaN           NaN           50
mean         5.843333      3.054000       3.758667      1.198667          NaN
std          0.828066      0.433594       1.764420      0.763161          NaN
min          4.300000      2.000000       1.000000      0.100000          NaN
25%          5.100000      2.800000       1.600000      0.300000          NaN
50%          5.800000      3.000000       4.350000      1.300000          NaN
75%          6.400000      3.300000       5.100000      1.800000          NaN
max          7.900000      4.400000       6.900000      2.500000          NaN

3.
Пропусков в датасете нет. Категориальный признак один, и это target столбец. Он не будет учавствовать в обучении, так что применим Label Encoding. ну и заодно сразу разделим датасет на Features и Target. Масштабировать ничего не надо, так как все признаки лежат примерно в одном диапазоне.

In [32]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(df["Species"])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
X = df.copy().drop(["Species"], axis=1)
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id
1              5.1           3.5            1.4           0.2
2              4.9           3.0            1.4           0.2
3              4.7           3.2            1.3           0.2
4              4.6           3.1            1.5           0.2
5              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
146            6.7           3.0            5.2           2.3
147            6.3           2.5            5.0           1.9
148            6.5           3.0            5.2           2.0
149            6.2           3.4            5.4           2.3
150            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

Далее разделим данные на train, validation и test.

Выделение test:

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=0, stratify=y)

Выделение validation:

In [35]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, train_size=0.75, random_state=0, stratify=y_train)

Для kNN важно масштабирование, так как оно уравнивает важность признаков.

Если подбирать параметр на тестовой выборке, то можно переобучить модель. Это происходит потому что параметр подгоняется под определенные данные. Поэтому на test выборке нельзя подбирать параметры. А чтобы не подбирать их "на глаз" на тренировочной выборке, можно разделить датасет на train, validation и test, что я и сделал выше. Тогда можно на validation выборке чуть точнее подобрать параметр, а на test выборке проверить работоспособность модели. Однако и этого может быть мало, тогда можно использовать кросс-валидацию и прочее.

4.

In [36]:
class kNN(BaseEstimator):
    __metrics_list = ["euclidean", "manhattan", "minkowski", "cosine"]
    __weights_list = ["uniform", "distance"]

    def __init__(self, train_destination_array=None, train_category_array=None, n_neighbours=3, metric="euclidean", weights="uniform", *, p=3):
        self.__train_destination_array = np.asarray(train_destination_array)
        self.__train_category_array = np.asarray(train_category_array)
        
        if n_neighbours > 0:
            self.__n_neighbours = n_neighbours
        else:
            raise Exception("The number of the nearest neighbours can't be less than 1.")
        
        if metric in self.__metrics_list:
            self.__metric = metric
        else:
            raise Exception("There's no such metric.")
        
        if weights in self.__weights_list:
            self.__weights = weights
        else:
            raise Exception("You can use only \"unform\" or \"distance\" as weights.")
        
        if p >= 1:
            self.__p = p
        else:
            raise Exception("The parameter of the Minkowski metric can't be less than 1.")
        
    @property
    def train_destination_array(self):
        return self.__train_destination_array
        
    @train_destination_array.setter
    def train_destination_array(self, train_destination_array):
        self.__train_destination_array = train_destination_array

    @property
    def train_category_array(self):
        return self.__train_category_array
        
    @train_category_array.setter
    def train_category_array(self, train_category_array):
        self.__train_category_array = train_category_array

# check the shape of the arrays!!!!!!!!!!

    @property
    def n_neighbours(self):
        return self.__n_neighbours
    
    @n_neighbours.setter
    def n_neighbours(self, n_neighbours):
        if n_neighbours > 0:
            self.__n_neighbours = n_neighbours
        else: 
            raise Exception("The numbers of the nearest neighbours can't be less than 1.")
        
    @property
    def metric(self):
        return self.__metric
        
    @metric.setter
    def metric(self, metric):
        if metric in self.__metrics_list:
            self.__metric = metric
        else:
            raise Exception("There's no such metric.")
    
    @property
    def weights(self):
        return self.__weights
        
    @weights.setter
    def weights(self, weights):
        if weights in self.__weights_list:
            self.__weights = weights
        else:
            raise Exception("You can use only \"unform\" or \"distance\" as weights.")
        
    @property
    def p(self):
        return self.__p
        
    @p.setter
    def p(self, p):
        if p >= 1:
            self.__p = p
        else:
            raise Exception("The parameter of the Minkowski metric can't be less than 1.")
        
    def destination(self, target_array):
        target_array = np.asarray(target_array)
        if self.__metric == "euclidean":
            return np.sqrt(np.sum((target_array[:, np.newaxis, :] - self.__train_destination_array[np.newaxis, :, :]) ** 2, axis = 2))
        elif self.__metric == "manhattan":
            return np.sum(np.abs((target_array[:, np.newaxis, :] - self.__train_destination_array[np.newaxis, :, :])), axis=2)
        elif self.__metric == "minkowski":
            return np.sum(np.abs(target_array[:, np.newaxis, :] - self.__train_destination_array[np.newaxis, :, :]) ** self.__p, axis = 2) ** (1/self.__p)
        elif self.__metric == "cosine":
            return 1 - ((target_array @ self.__train_destination_array.T) / ((np.sqrt(np.sum(target_array**2, axis=1) + 1e-10))[:, np.newaxis] * (np.sqrt(np.sum(self.__train_destination_array**2, axis=1) + 1e-10))[np.newaxis, :]))
        else:
            raise ValueError("Unknown metric")
        
    def fit(self, train_destination_array, train_category_array):
        self.__train_destination_array = np.asarray(train_destination_array)
        self.__train_category_array = np.asarray(train_category_array)
        return self
        
    def predict(self, target_array):
        if self.__weights=="uniform":
            target_array = np.asarray(target_array)
            D = self.destination(target_array)
            idx = np.argsort(D)
            y_nearest = np.take_along_axis(self.__train_category_array[np.newaxis, :], idx)
            if self.__n_neighbours < y_nearest.shape[1]:
                y_nearest = y_nearest[:, :self.__n_neighbours]
            return np.apply_along_axis(lambda row: np.bincount(row).argmax(), axis=1, arr=y_nearest)
        elif self.__weights=="distance":
            target_array = np.asarray(target_array)
            D = self.destination(target_array)
            idx = np.argsort(D)
            y_nearest = np.take_along_axis(self.__train_category_array[np.newaxis, :], idx)
            D = np.take_along_axis(self.__train_category_array[np.newaxis, :], idx)
            D = 1 / (D + 1e-10)
            if self.__n_neighbours < y_nearest.shape[1]:
                y_nearest = y_nearest[:, :self.__n_neighbours]
                D = D[:, :self.__n_neighbours]
            y_pred = np.empty(D.shape[0])
            for i in range(0, D.shape[0]):
                res = pandas.DataFrame({'key': y_nearest[i], 'val': D[i]}).groupby('key')['val'].sum().to_dict()
                y_pred[i] = max(res, key=res.get)
            return y_pred

In [53]:
knn = kNN(X_train, y_train, 20, metric = "cosine", weights="uniform", p=100)
R = knn.predict(X_test)
R

array([0, 1, 0, 2, 0, 1, 2, 0, 0, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 0, 0, 2,
       2, 2, 0, 1, 1, 2, 0, 0])

In [54]:
y_test

array([0, 1, 0, 2, 0, 1, 2, 0, 0, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 0, 0, 2,
       2, 2, 0, 1, 1, 2, 0, 0])

In [55]:
print(metrics.accuracy_score(y_test, R))

1.0

In [56]:
print(metrics.f1_score(R, y_test, average=None))

[1. 1. 1.]

In [41]:
knn.get_params()

{'metric': 'cosine',
 'n_neighbours': 15,
 'p': 100,
 'train_category_array': array([0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 1, 0,
        2, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 0,
        1, 1, 2, 0, 2, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 2, 0, 1,
        0, 1, 1, 1, 2, 0, 1, 0, 1, 2, 1, 1, 0, 0, 1, 0, 1, 2, 2, 1, 2, 0,
        1, 0]),
 'train_destination_array': array([[5.7, 3.8, 1.7, 0.3],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [7.9, 3.8, 6.4, 2. ],
        [6. , 2.2, 5. , 1.5],
        [4.4, 2.9, 1.4, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.4, 3.7, 1.5, 0.2],
        [6.7, 3.3, 5.7, 2.5],
        [6.3, 2.5, 5. , 1.9],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.5, 1.4, 0.3],
        [7.2, 3.6, 6.1, 2.5],
        [5.4, 3.4, 1.5, 0.4],
        [6.8, 2.8, 4.8, 1.4],
        [5. , 3.3, 1.4, 0.2],
        [6.5, 3. , 5.5, 1.8],
        [6.5, 3.2, 5.1, 2. ],
        [4.9, 2.4, 3.3, 1. ],
        [5.7, 4.4, 1.5, 0.4],
        [6. , 3. , 4.8, 1.8],
        [6. , 2.2, 4. , 1. ],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.9, 3.6, 1.3],
        [5.2, 3.4, 1.4, 0.2],
        [6.3, 2.5, 4.9, 1.5],
        [5.4, 3.9, 1.7, 0.4],
        [5. , 3.6, 1.4, 0.2],
        [6.5, 3. , 5.8, 2.2],
        [5. , 3.2, 1.2, 0.2],
        [7.3, 2.9, 6.3, 1.8],
        [6.4, 3.1, 5.5, 1.8],
        [4.3, 3. , 1.1, 0.1],
        [7.2, 3.2, 6. , 1.8],
        [4.9, 2.5, 4.5, 1.7],
        [5. , 3.4, 1.6, 0.4],
        [6.2, 3.4, 5.4, 2.3],
        [7.1, 3. , 5.9, 2.1],
        [5.8, 2.8, 5.1, 2.4],
        [6.2, 2.9, 4.3, 1.3],
        [4.4, 3.2, 1.3, 0.2],
        [5.6, 2.5, 3.9, 1.1],
        [6.3, 2.3, 4.4, 1.3],
        [6.8, 3. , 5.5, 2.1],
        [4.8, 3.4, 1.9, 0.2],
        [6.3, 2.8, 5.1, 1.5],
        [5.7, 3. , 4.2, 1.2],
        [6.1, 3. , 4.9, 1.8],
        [6.3, 2.7, 4.9, 1.8],
        [6.1, 2.9, 4.7, 1.4],
        [5.1, 2.5, 3. , 1.1],
        [4.9, 3.1, 1.5, 0.1],
        [6.8, 3.2, 5.9, 2.3],
        [5.8, 4. , 1.2, 0.2],
        [6. , 2.9, 4.5, 1.5],
        [4.4, 3. , 1.3, 0.2],
        [5.6, 2.7, 4.2, 1.3],
        [6. , 2.7, 5.1, 1.6],
        [6.7, 3.1, 5.6, 2.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.4, 2.8, 5.6, 2.1],
        [4.6, 3.6, 1. , 0.2],
        [6.1, 2.8, 4.7, 1.2],
        [4.5, 2.3, 1.3, 0.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2.3, 3.3, 1. ],
        [6.1, 3. , 4.6, 1.4],
        [6.9, 3.2, 5.7, 2.3],
        [4.7, 3.2, 1.3, 0.2],
        [5.5, 2.4, 3.8, 1.1],
        [5. , 3.5, 1.3, 0.3],
        [6.7, 3. , 5. , 1.7],
        [7.7, 3.8, 6.7, 2.2],
        [6.3, 3.3, 4.7, 1.6],
        [5.8, 2.6, 4. , 1.2],
        [4.9, 3.1, 1.5, 0.1],
        [4.9, 3. , 1.4, 0.2],
        [5.9, 3.2, 4.8, 1.8],
        [5.1, 3.3, 1.7, 0.5],
        [6.1, 2.8, 4. , 1.3],
        [6.7, 2.5, 5.8, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [6.4, 2.9, 4.3, 1.3],
        [7.7, 3. , 6.1, 2.3],
        [5.3, 3.7, 1.5, 0.2],
        [5.9, 3. , 4.2, 1.5],
        [5.4, 3.9, 1.3, 0.4]]),
 'weights': 'distance'}

In [ ]:
params = [{
    'metric': ['euclidean', 'manhattan', 'cosine'],
    'n_neighbours': list(range(1, 50)),
    'weights': ['uniform', 'distance']
},
{
    'metric': ['minkowski'],
    'n_neighbours': list(range(1, 50)),
    'p': list(range(3, 15)),
    'weights': ['uniform', 'distance']
}
]

gs = GridSearchCV(kNN(), params, scoring='f1_macro', cv=5, n_jobs=10)
gs.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=kNN(train_category_array=array(None, dtype=object),
                           train_destination_array=array(None, dtype=object)),
             n_jobs=10,
             param_grid=[{'metric': ['euclidean', 'manhattan', 'cosine'],
                          'n_neighbours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                           12, 13, 14, 15, 16, 17, 18, 19, 20,
                                           21, 22, 23, 24, 25, 26, 27, 28, 29,
                                           30, ...],
                          'weights': ['uniform', 'distance']},
                         {'metric': ['minkowski'],
                          'n_neighbours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                           12, 13, 14, 15, 16, 17, 18, 19, 20,
                                           21, 22, 23, 24, 25, 26, 27, 28, 29,
                                           30, ...],
                          'p': [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
                          'weights': ['uniform', 'distance']}],
             scoring='f1_macro')

In [ ]:
results = pandas.DataFrame(gs.cv_results_)

In [65]:
minkowski_params_results = results[(results['param_metric'] == 'euclidean') & (results['param_weights'] == 'uniform')]
minkowski_params_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbours,param_weights,param_p,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001434,0.000168,0.003908,0.000496,euclidean,1,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 1, 'we...",0.925926,0.822222,0.910714,0.940741,0.885714,0.897063,0.041610,470
2,0.001077,0.000079,0.003815,0.000193,euclidean,2,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 2, 'we...",0.850000,0.771429,0.821429,0.940741,0.940741,0.864868,0.066862,723
4,0.000892,0.000151,0.003375,0.000661,euclidean,3,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 3, 'we...",0.850000,0.932773,0.821429,0.940741,0.885714,0.886131,0.046151,567
6,0.000736,0.000101,0.002639,0.000233,euclidean,4,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 4, 'we...",0.850000,0.875000,0.821429,0.940741,0.940741,0.885582,0.048122,593
8,0.000712,0.000076,0.002543,0.000181,euclidean,5,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 5, 'we...",1.000000,0.875000,0.821429,0.940741,0.940741,0.915582,0.061488,67
10,0.000636,0.000021,0.002436,0.000035,euclidean,6,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 6, 'we...",0.925926,0.875000,0.821429,0.940741,0.940741,0.900767,0.046448,385
12,0.000649,0.000123,0.002818,0.000291,euclidean,7,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 7, 'we...",0.925926,0.875000,0.866667,0.940741,0.940741,0.909815,0.032392,189
14,0.000754,0.000139,0.003319,0.000569,euclidean,8,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 8, 'we...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
16,0.000691,0.000149,0.003052,0.000517,euclidean,9,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 9, 'we...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
18,0.000760,0.000087,0.003353,0.000203,euclidean,10,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 10, 'w...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
20,0.000632,0.000156,0.003001,0.000680,euclidean,11,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 11, 'w...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
22,0.000706,0.000057,0.003557,0.000066,euclidean,12,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 12, 'w...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
24,0.000728,0.000087,0.003371,0.000284,euclidean,13,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 13, 'w...",0.925926,0.940741,0.821429,0.940741,0.940741,0.913915,0.046598,97
26,0.000717,0.000147,0.003281,0.000587,euclidean,14,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 14, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
28,0.000755,0.000150,0.003520,0.000641,euclidean,15,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 15, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
30,0.000752,0.000066,0.004577,0.001675,euclidean,16,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 16, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
32,0.000709,0.000096,0.003202,0.000477,euclidean,17,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 17, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
34,0.000796,0.000051,0.003493,0.000523,euclidean,18,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 18, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
36,0.000741,0.000084,0.003866,0.000521,euclidean,19,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 19, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
38,0.000739,0.000067,0.003296,0.000535,euclidean,20,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 20, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
40,0.000800,0.000160,0.003736,0.000210,euclidean,21,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 21, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
42,0.000792,0.000066,0.003574,0.000207,euclidean,22,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 22, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
44,0.000798,0.000068,0.003742,0.000160,euclidean,23,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 23, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
46,0.000752,0.000065,0.003894,0.000155,euclidean,24,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 24, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
48,0.000639,0.000149,0.003285,0.000593,euclidean,25,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 25, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
50,0.000758,0.000047,0.003861,0.000200,euclidean,26,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 26, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
52,0.000673,0.000111,0.003595,0.000231,euclidean,27,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 27, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
54,0.000688,0.000094,0.003497,0.000435,euclidean,28,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 28, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
56,0.000695,0.000103,0.003395,0.000570,euclidean,29,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 29, 'w...",0.925926,0.885714,0.821429,0.940741,0.940741,0.902910,0.045447,195
58,0.000624,0.000153,0.002952,0.000585,euclidean,30,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 30, 'w...",0.925926,0.885714,0.821429,1.000000,0.940741,0.914762,0.059363,80
60,0.000739,0.000061,0.003702,0.000157,euclidean,31,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 31, 'w...",0.925926,0.885714,0.821429,1.000000,0.832168,0.893047,0.065436,500
62,0.000626,0.000136,0.003124,0.000756,euclidean,32,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 32, 'w...",0.925926,0.885714,0.699176,1.000000,0.832168,0.868597,0.100873,711
64,0.000783,0.000047,0.003817,0.000077,euclidean,33,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 33, 'w...",0.925926,0.885714,0.699176,0.940741,0.832168,0.856745,0.087307,776
66,0.000654,0.000149,0.003203,0.000675,euclidean,34,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 34, 'w...",0.925926,0.832168,0.699176,0.940741,0.832168,0.846036,0.086376,868
68,0.000698,0.000078,0.003620,0.000225,euclidean,35,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 35, 'w...",0.925926,0.885714,0.699176,0.940741,0.832168,0.856745,0.087307,776
70,0.000620,0.000112,0.003275,0.000538,euclidean,36,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 36, 'w...",0.925926,0.832168,0.699176,1.000000,0.885714,0.868597,0.100873,711
72,0.000722,0.000032,0.003648,0.000096,euclidean,37,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 37, 'w...",0.925926,0.832168,0.699176,0.940741,0.832168,0.846036,0.086376,868
74,0.000658,0.000067,0.003232,0.000447,euclidean,38,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 38, 'w...",0.925926,0.720280,0.699176,0.940741,0.832168,0.823658,0.100422,957
76,0.000730,0.000117,0.003474,0.000371,euclidean,39,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 39, 'w...",0.850000,0.720280,0.699176,0.940741,0.832168,0.808473,0.088887,1006
78,0.000748,0.000048,0.003619,0.000141,euclidean,40,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 40, 'w...",0.850000,0.657143,0.699176,1.000000,0.832168,0.807697,0.121501,1008
80,0.000764,0.000089,0.003614,0.000206,euclidean,41,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 41, 'w...",0.850000,0.720280,0.699176,0.777778,0.832168,0.775880,0.059398,1078
82,0.000602,0.000146,0.002976,0.000578,euclidean,42,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 42, 'w...",0.850000,0.585185,0.452381,0.885714,0.832168,0.721090,0.171308,1152
84,0.000577,0.000097,0.002735,0.000622,euclidean,43,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 43, 'w...",0.802614,0.777778,0.452381,0.885714,0.832168,0.750131,0.153158,1087
86,0.000656,0.000120,0.003485,0.000295,euclidean,44,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 44, 'w...",0.390351,0.500000,0.452381,0.885714,0.832168,0.612123,0.205204,1206
88,0.000754,0.000021,0.003768,0.000167,euclidean,45,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 45, 'w...",0.384314,0.500000,0.452381,0.720280,0.585185,0.528432,0.116094,1231
90,0.000762,0.000051,0.003920,0.000176,euclidean,46,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 46, 'w...",0.390351,0.500000,0.452381,0.720280,0.585185,0.529639,0.114610,1227
92,0.000757,0.000055,0.003708,0.000079,euclidean,47,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 47, 'w...",0.384314,0.500000,0.452381,0.720280,0.585185,0.528432,0.116094,1231
94,0.000754,0.000177,0.003291,0.000519,euclidean,48,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 48, 'w...",0.390351,0.500000,0.452381,0.720280,0.585185,0.529639,0.114610,1227
96,0.000785,0.000085,0.003702,0.000103,euclidean,49,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 49, 'w...",0.333333,0.500000,0.452381,0.657143,0.585185,0.505608,0.111210,1285

5.

In [63]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbours,param_weights,param_p,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001434,0.000168,0.003908,0.000496,euclidean,1,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 1, 'we...",0.925926,0.822222,0.910714,0.940741,0.885714,0.897063,0.041610,470
1,0.001840,0.000161,0.022275,0.001043,euclidean,1,distance,NaN,"{'metric': 'euclidean', 'n_neighbours': 1, 'we...",0.925926,0.822222,0.910714,0.940741,0.885714,0.897063,0.041610,470
2,0.001077,0.000079,0.003815,0.000193,euclidean,2,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 2, 'we...",0.850000,0.771429,0.821429,0.940741,0.940741,0.864868,0.066862,723
3,0.001032,0.000162,0.021519,0.002036,euclidean,2,distance,NaN,"{'metric': 'euclidean', 'n_neighbours': 2, 'we...",0.850000,0.771429,0.821429,0.940741,0.940741,0.864868,0.066862,723
4,0.000892,0.000151,0.003375,0.000661,euclidean,3,uniform,NaN,"{'metric': 'euclidean', 'n_neighbours': 3, 'we...",0.850000,0.932773,0.821429,0.940741,0.885714,0.886131,0.046151,567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0.000693,0.000106,0.018836,0.001302,minkowski,49,distance,12.0,"{'metric': 'minkowski', 'n_neighbours': 49, 'p...",0.538462,0.166667,0.095238,0.166667,0.166667,0.226740,0.158297,1456
1466,0.000664,0.000097,0.003289,0.001296,minkowski,49,uniform,13.0,"{'metric': 'minkowski', 'n_neighbours': 49, 'p...",0.390351,0.500000,0.452381,0.657143,0.585185,0.517012,0.094651,1247
1467,0.000679,0.000102,0.018021,0.001476,minkowski,49,distance,13.0,"{'metric': 'minkowski', 'n_neighbours': 49, 'p...",0.538462,0.166667,0.095238,0.166667,0.166667,0.226740,0.158297,1456
1468,0.000685,0.000092,0.002808,0.000523,minkowski,49,uniform,14.0,"{'metric': 'minkowski', 'n_neighbours': 49, 'p...",0.390351,0.500000,0.452381,0.657143,0.585185,0.517012,0.094651,1247
1469,0.000733,0.000086,0.017766,0.001205,minkowski,49,distance,14.0,"{'metric': 'minkowski', 'n_neighbours': 49, 'p...",0.538462,0.166667,0.095238,0.166667,0.166667,0.226740,0.158297,1456

In [62]:
results[(results['param_metric'] == 'cosine') & (results['param_weights'] == 'uniform') & (results['param_n_neighbours'] == 20)]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbours,param_weights,param_p,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
234,0.000635,0.000137,0.002947,0.000756,cosine,20,uniform,NaN,"{'metric': 'cosine', 'n_neighbours': 20, 'weig...",1.0,1.0,1.0,0.940741,0.940741,0.976296,0.029031,1